In [3]:
# pip install -U scikit-learn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
# pip install tensorflow

Note: you may need to restart the kernel to use updated packages.Collecting tensorflow
  Using cached tensorflow-2.17.0-cp311-cp311-win_amd64.whl (2.0 kB)
  Using cached tensorflow_intel-2.17.0-cp311-cp311-win_amd64.whl (385.0 MB)
  Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Using cached gast-0.6.0-py3-none-any.whl (21 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
  Using cached h5py-3.11.0-cp311-cp311-win_amd64.whl (3.0 MB)
  Using cached ml_dtypes-0.4.0-cp311-cp311-win_amd64.whl (126 kB)
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
  Using cached grpcio-1.65.4-cp311-cp311-win_amd64.whl (4.1 MB)
  Using cached tensorboard-2.17.0-py3-none-any.whl (5.5 MB)
  Using cached keras-3.4.1-py3-none-any.whl (1.1 MB)
  Using cached rich-13.7.1-py3-none-any.whl (240 kB)
  Using cached Markdown-3.6-py3-none-any.whl (105 kB)
  Using cached markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
  Using cache


[notice] A new release of pip available: 22.3.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
pip list

Note: you may need to restart the kernel to use updated packages.
Package                      Version
---------------------------- --------------
absl-py                      2.1.0
anyio                        4.4.0
argon2-cffi                  23.1.0
argon2-cffi-bindings         21.2.0
arrow                        1.3.0
asttokens                    2.4.1
astunparse                   1.6.3
async-lru                    2.0.4
attrs                        23.2.0
audioread                    3.0.1
Babel                        2.15.0
beautifulsoup4               4.12.3
bleach                       6.1.0
certifi                      2024.7.4
cffi                         1.16.0
charset-normalizer           3.3.2
colorama                     0.4.6
comm                         0.2.2
contourpy                    1.2.1
cycler                       0.12.1
debugpy                      1.8.2
decorator                    5.1.1
defusedxml                   0.7.1
executing                    2.0.1
fas


[notice] A new release of pip available: 22.3.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


# 1. Define Imports

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# 2. Load Data

In [2]:
# Load the data
human_df = pd.read_csv('result\human_mfcc_features.csv')
synthetic_df = pd.read_csv('result\synthetic_mfcc_features.csv')

# 3. Label Data

In [3]:
human_df['label'] = 1
synthetic_df['label'] = 0

In [4]:
# Combine the data
# Reduce to 6 decimals and round up
# Uses Scientific notation to move decimal point
data_df = pd.concat([human_df, synthetic_df], ignore_index=True)

In [5]:
data_df

file_name  mfcc_feature1  mfcc_feature2  mfcc_feature3  \
0           spanish86.mp3    -323.919922     103.207230      -0.064050   
1            swedish4.mp3    -295.136810      69.772408       3.775682   
2           tagalog12.mp3    -352.794800      85.699890       3.341066   
3          taiwanese6.mp3    -287.268250     122.900909       5.998333   
4             tajiki1.mp3    -338.770752      62.378841     -21.894604   
5              thai10.mp3    -221.882736      78.358940      -2.575354   
6           tigrigna5.mp3    -353.374664     108.476105      -6.168679   
7            turkish6.mp3    -303.188995     127.196083      -6.518612   
8              urdu10.mp3    -246.812027     132.497665      -6.538076   
9            yiddish3.mp3    -308.435211     140.867706     -20.193178   
10   spanish86_cloned.mp3    -253.368515     135.128464      -7.459697   
11    swedish4_cloned.mp3    -166.629471      89.696144       0.042984   
12   tagalog12_cloned.mp3    -226.903900     105.014870     -12.404805   
13  taiwanese6_cloned.mp3    -242.969666     140.078857      -0.760939   
14     tajiki1_cloned.mp3    -171.743820      81.141678     -36.365517   
15      thai10_cloned.mp3    -193.134186      84.791306      -3.990597   
16   tigrigna5_cloned.mp3    -245.046997     126.281441     -15.192507   
17    turkish6_cloned.mp3    -253.869415     138.880753     -10.747830   
18      urdo10_cloned.mp3    -196.868088     144.456467     -16.745396   
19     yidish3_cloned.mp3    -188.208832     163.903702     -39.247017   

    mfcc_feature4  mfcc_feature5  mfcc_feature6  mfcc_feature7  mfcc_feature8  \
0       28.463770      -2.065437      -0.414627     -17.255842     -13.738381   
1       39.351192      -1.443911      12.909846      -6.823179       5.405806   
2       22.898197       0.309346       4.346154      -9.252878      -9.979355   
3       40.535263      -9.271994      -3.287776     -28.686665       6.240179   
4       29.338533      -9.406798       4.938019     -10.252720       8.488515   
5       50.000839      -4.789689      13.335052      -9.493750      10.136446   
6       26.282919      10.874166       5.547210     -28.736158     -16.075092   
7       40.052338      12.405135       3.574269      -2.328453       2.114575   
8       42.911251      -1.475313       0.302820     -28.255020      -4.708546   
9       29.125114      -0.971515      13.070960     -16.686201       0.131260   
10      32.957859      -7.852261       0.968793     -17.303911     -11.520423   
11      41.714081      -1.821101      10.321057      -4.918056       7.076171   
12      25.706635      -5.091922       5.366620      -9.952550     -11.558692   
13      37.641281     -15.399357      -5.872347     -31.609529       1.130655   
14      36.395767     -16.216465       1.375686     -10.973686      11.151711   
15      57.027721     -11.444659      14.400137     -11.834125      16.677826   
16      27.744270       5.047342      10.738227     -28.832069     -11.213750   
17      36.249374       8.095733      -0.221491       0.252511      -1.461823   
18      38.622585      -9.405319       2.075253     -28.732182       3.006678   
19      28.025990      -4.839808       9.108365     -19.743595       1.950383   

    mfcc_feature9  ...  mfcc_feature31  mfcc_feature32  mfcc_feature33  \
0      -18.472324  ...    6.419813e-09    6.198440e-09    3.099220e-09   
1      -16.720444  ...   -6.014163e-09    5.154996e-09    1.718332e-09   
2      -21.909899  ...   -3.482186e-03   -2.239494e-03   -7.414591e-04   
3      -11.587509  ...    2.758056e-09   -4.596759e-10   -1.838704e-09   
4      -18.001724  ...   -3.581220e-03    2.307348e-04    1.292295e-03   
5      -15.041023  ...   -8.619611e-03    3.412028e-03    1.266686e-03   
6      -15.995757  ...    2.275310e-03    1.429119e-03   -4.441070e-03   
7      -12.410596  ...    2.295402e-03    2.924155e-03    1.935776e-03   
8      -25.839319  ...   -3.562395e-03    2.969973e-03   -1.455065e-02   
9      -14.618179  

In [7]:
data_df["label"].value_counts()

label
1    10
0    10
Name: count, dtype: int64

In [8]:
# Shuffle the data
data_df = data_df.sample(frac=1).reset_index(drop=True)

In [9]:
data_df

file_name  mfcc_feature1  mfcc_feature2  mfcc_feature3  \
0              thai10.mp3    -221.882736      78.358940      -2.575354   
1           tagalog12.mp3    -352.794800      85.699890       3.341066   
2            yiddish3.mp3    -308.435211     140.867706     -20.193178   
3    spanish86_cloned.mp3    -253.368515     135.128464      -7.459697   
4      yidish3_cloned.mp3    -188.208832     163.903702     -39.247017   
5            swedish4.mp3    -295.136810      69.772408       3.775682   
6             tajiki1.mp3    -338.770752      62.378841     -21.894604   
7           spanish86.mp3    -323.919922     103.207230      -0.064050   
8          taiwanese6.mp3    -287.268250     122.900909       5.998333   
9       urdo10_cloned.mp3    -196.868088     144.456467     -16.745396   
10  taiwanese6_cloned.mp3    -242.969666     140.078857      -0.760939   
11             urdu10.mp3    -246.812027     132.497665      -6.538076   
12   tagalog12_cloned.mp3    -226.903900     105.014870     -12.404805   
13      thai10_cloned.mp3    -193.134186      84.791306      -3.990597   
14          tigrigna5.mp3    -353.374664     108.476105      -6.168679   
15           turkish6.mp3    -303.188995     127.196083      -6.518612   
16    turkish6_cloned.mp3    -253.869415     138.880753     -10.747830   
17    swedish4_cloned.mp3    -166.629471      89.696144       0.042984   
18   tigrigna5_cloned.mp3    -245.046997     126.281441     -15.192507   
19     tajiki1_cloned.mp3    -171.743820      81.141678     -36.365517   

    mfcc_feature4  mfcc_feature5  mfcc_feature6  mfcc_feature7  mfcc_feature8  \
0       50.000839      -4.789689      13.335052      -9.493750      10.136446   
1       22.898197       0.309346       4.346154      -9.252878      -9.979355   
2       29.125114      -0.971515      13.070960     -16.686201       0.131260   
3       32.957859      -7.852261       0.968793     -17.303911     -11.520423   
4       28.025990      -4.839808       9.108365     -19.743595       1.950383   
5       39.351192      -1.443911      12.909846      -6.823179       5.405806   
6       29.338533      -9.406798       4.938019     -10.252720       8.488515   
7       28.463770      -2.065437      -0.414627     -17.255842     -13.738381   
8       40.535263      -9.271994      -3.287776     -28.686665       6.240179   
9       38.622585      -9.405319       2.075253     -28.732182       3.006678   
10      37.641281     -15.399357      -5.872347     -31.609529       1.130655   
11      42.911251      -1.475313       0.302820     -28.255020      -4.708546   
12      25.706635      -5.091922       5.366620      -9.952550     -11.558692   
13      57.027721     -11.444659      14.400137     -11.834125      16.677826   
14      26.282919      10.874166       5.547210     -28.736158     -16.075092   
15      40.052338      12.405135       3.574269      -2.328453       2.114575   
16      36.249374       8.095733      -0.221491       0.252511      -1.461823   
17      41.714081      -1.821101      10.321057      -4.918056       7.076171   
18      27.744270       5.047342      10.738227     -28.832069     -11.213750   
19      36.395767     -16.216465       1.375686     -10.973686      11.151711   

    mfcc_feature9  ...  mfcc_feature31  mfcc_feature32  mfcc_feature33  \
0      -15.041023  ...   -8.619611e-03    3.412028e-03    1.266686e-03   
1      -21.909899  ...   -3.482186e-03   -2.239494e-03   -7.414591e-04   
2      -14.618179  ...    6.784475e-03   -6.051512e-03   -1.078432e-03   
3      -19.510910  ...   -1.646412e-02   -2.644841e-03    5.179129e-03   
4      -19.720686  ...    1.940770e-02    2.402905e-02    1.171768e-02   
5      -16.720444  ...   -6.014163e-09    5.154996e-09    1.718332e-09   
6      -18.001724  ...   -3.581220e-03    2.307348e-04    1.292295e-03   
7      -18.472324  ...    6.419813e-09    6.198440e-09    3.099220e-09   
8      -11.587509  ...    2.758056e-09   -4.596759e-10   -1.838704e-09   
9      -22.900566  

In [10]:
# Split features and labels
X = data_df.drop(columns=['file_name', 'label']).values
y = data_df['label'].values

In [11]:
X

array([[-2.21882736e+02,  7.83589401e+01, -2.57535434e+00,
         5.00008392e+01, -4.78968859e+00,  1.33350515e+01,
        -9.49374962e+00,  1.01364460e+01, -1.50410233e+01,
         9.87045860e+00, -7.29820490e+00,  6.12554884e+00,
        -4.42603064e+00,  5.83163742e-03, -3.33883502e-02,
         1.88967958e-02,  1.42798377e-02, -7.36614596e-03,
         1.67313050e-02,  1.38979061e-02,  3.41064371e-02,
        -4.07408690e-03,  3.21312714e-03, -1.32550858e-02,
        -8.97478126e-03, -3.28161800e-03, -1.27487658e-02,
        -1.68232452e-02,  6.15379959e-03,  8.96572508e-03,
        -8.61961115e-03,  3.41202761e-03,  1.26668578e-03,
         2.82472605e-03,  4.74082865e-03,  4.98343911e-03,
        -3.91166471e-03,  3.08665447e-03,  5.14629809e-03],
       [-3.52794800e+02,  8.56998901e+01,  3.34106588e+00,
         2.28981972e+01,  3.09345663e-01,  4.34615374e+00,
        -9.25287819e+00, -9.97935486e+00, -2.19098988e+01,
        -3.91855335e+00, -1.15468550e+01, -7.26676035e+

# 4. Split into training and testing sets

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
y_test

array([1, 0, 1, 1], dtype=int64)

# 5. Restructure for CNN

In [14]:
# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [18]:
X_train = X_train.reshape((X_train.shape[0], X_train.shape[1], 1, 1))
X_test = X_test.reshape((X_test.shape[0], X_test.shape[1], 1, 1))

In [19]:
X_train

array([[[[-5.45282032e-01]],

        [[ 2.32398263e-01]],

        [[ 1.41288471e+00]],

        [[ 7.29782394e-01]],

        [[-6.42191826e-01]],

        [[-1.30038142e+00]],

        [[-1.08322478e+00]],

        [[ 7.73471454e-01]],

        [[ 1.54251163e+00]],

        [[-7.00009062e-01]],

        [[ 1.76642637e+00]],

        [[-1.04502488e+00]],

        [[ 1.86576754e-01]],

        [[-4.47013303e-01]],

        [[ 5.34342160e-02]],

        [[ 4.68716025e-01]],

        [[-8.53570079e-02]],

        [[ 6.10993094e-01]],

        [[ 3.14035147e-02]],

        [[ 4.14154149e-01]],

        [[-8.35187348e-02]],

        [[ 7.33690364e-01]],

        [[-8.03737558e-02]],

        [[ 3.36783579e-01]],

        [[ 3.10272286e-01]],

        [[ 5.81749757e-01]],

        [[-2.21203311e-01]],

        [[ 1.26413127e-01]],

        [[ 6.15701967e-01]],

        [[ 4.76922137e-02]],

        [[-9.54056909e-02]],

        [[-2.81644435e-02]],

        [[ 1.54874980e-02]],

        [[

# 6. Define CNN Model

In [42]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, Input

# Define the model
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(X_train.shape[1], 1, 1), padding='same'),
    MaxPooling2D((2, 1)),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 1)),
    Conv2D(128, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 1)),
    Conv2D(256, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 1)),
    Flatten(),
    Dense(256, activation='relu'),
    Dropout(0.5),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(1, activation='sigmoid')
])

# model = Sequential([
#     Input(shape=(X_train.shape[1], X_train.shape[2], 1)),  # Define the input shape using the Input layer
#     Conv2D(32, (3, 3), activation='relu', padding='same'),
#     MaxPooling2D((2, 1)),
#     Conv2D(64, (3, 3), activation='relu', padding='same'),
#     MaxPooling2D((2, 1)),
#     Conv2D(128, (3, 3), activation='relu', padding='same'),
#     MaxPooling2D((2, 1)),
#     Conv2D(256, (3, 3), activation='relu', padding='same'),
#     MaxPooling2D((2, 1)),
#     Flatten(),
#     Dense(256, activation='relu'),
#     Dropout(0.5),
#     Dense(128, activation='relu'),
#     Dropout(0.5),
#     Dense(1, activation='sigmoid')
# ])

# Compile
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.summary()

C:\Users\Jeleazar\Desktop\AudioClassificationFeatures\env\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (None, 39, 1, 32)           │             320 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ (None, 19, 1, 32)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 19, 1, 64)           │          18,496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_1 (MaxPooling2D)       │ (None, 9, 1, 64)            │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_2 (Conv2D)                    │ (None, 9, 1, 128)           │          73,856 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_2 (MaxPooling2D)       │ (None, 4, 1, 128)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_3 (Conv2D)                    │ (None, 4, 1, 256)           │         295,168 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_3 (MaxPooling2D)       │ (None, 2, 1, 256)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 512)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 256)                 │         131,328 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 256)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 128)                 │          32,896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 128)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │             129 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 552,193 (2.11 MB)

 Trainable params: 552,193 (2.11 MB)

 Non-trainable params: 0 (0.00 B)

# 7. Train the model

In [18]:
# Train the model
history = model.fit(X_train, y_train, epochs=20, batch_size=32, validation_split=0.2)

Epoch 1/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.8333 - loss: 0.4200 - val_accuracy: 1.0000 - val_loss: 0.3290
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.9167 - loss: 0.3613 - val_accuracy: 1.0000 - val_loss: 0.2835
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.9167 - loss: 0.3531 - val_accuracy: 1.0000 - val_loss: 0.2502
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.8333 - loss: 0.3654 - val_accuracy: 1.0000 - val_loss: 0.2913
Epoch 5/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.9167 - loss: 0.3869 - val_accuracy: 1.0000 - val_loss: 0.2531
Epoch 6/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 1.0000 - loss: 0.2304 - val_accuracy: 1.0000 - val_loss: 0.1641
Epoch 7/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.9167 - loss: 0.2164 - val_accuracy: 1.0000 - val_loss: 0.1048
Epoch 8/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 1.0000 - loss: 0.1627 - val_accuracy: 1.0000 - val_loss: 0.0765
Ep

# 8. Save the model

In [45]:
# Save the model
model.save('models/DeepFake_model.keras')

# 9. Load Model

In [20]:
from tensorflow.keras.models import load_model

# Load the model from Keras format
model = load_model('models/DeepFake_model.keras')

# 10. Evaluate the model

In [21]:
# Evaluate the model on the test set
test_loss, test_acc = model.evaluate(X_test, y_test)
print(f'Test Accuracy: {test_acc:.4f}')

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 549ms/step - accuracy: 1.0000 - loss: 0.4122
Test Accuracy: 1.0000


In [22]:
# Predict on new data
predictions = model.predict(X_test)
predicted_labels = (predictions > 0.5).astype(int)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step


In [23]:
predicted_labels

array([[1],
       [0],
       [1],
       [1]])

In [24]:
predictions

array([[0.60284793],
       [0.31000045],
       [0.6594207 ],
       [0.70090705]], dtype=float32)

In [22]:
y_test

array([0, 1, 0, 1], dtype=int64)

# Test single audio file (to fixxx)

In [25]:
mfcc_features = pd.read_csv('result\human_test.csv') #Human
# mfcc_features = pd.read_csv('result\human_test1.csv') #Human
# mfcc_features = pd.read_csv('result\human_test2.csv') #Human
# mfcc_features = pd.read_csv('result\synthetic_mfcc_features.csv') #AI
# mfcc_features = pd.read_csv('result\synthetic_test.csv') #AI
# mfcc_features = pd.read_csv('result\synthetic_test1.csv') #AI


mfcc_features = mfcc_features.drop(columns=['file_name']).values
num_features, num_timesteps = mfcc_features.shape
mfcc_features_reshaped = mfcc_features.reshape(1, num_timesteps, num_features, 1)

In [26]:
mfcc_features.shape

(1, 39)

In [27]:
mfcc_features_reshaped.shape

(1, 39, 1, 1)

In [28]:
mfcc_features_reshaped

array([[[[-3.48400024e+02]],

        [[ 1.08139557e+02]],

        [[ 1.78048706e+01]],

        [[ 2.18827076e+01]],

        [[ 1.58862507e+00]],

        [[ 8.21730900e+00]],

        [[ 4.71831381e-01]],

        [[ 2.03513527e+00]],

        [[-5.40455389e+00]],

        [[ 3.00045228e+00]],

        [[-1.73860621e+00]],

        [[ 3.98720932e+00]],

        [[-1.37868118e+00]],

        [[-2.17390880e-02]],

        [[-5.81611954e-02]],

        [[-1.60738267e-02]],

        [[-1.02617480e-02]],

        [[-1.86061580e-02]],

        [[ 1.96272833e-03]],

        [[ 3.98872234e-03]],

        [[ 6.90331915e-03]],

        [[ 1.84269389e-03]],

        [[ 6.05496066e-03]],

        [[ 8.97609803e-04]],

        [[ 9.85475257e-04]],

        [[ 1.83178065e-03]],

        [[-5.39894998e-02]],

        [[-1.56187760e-02]],

        [[-2.61521828e-03]],

        [[-1.08521339e-02]],

        [[-1.63697184e-03]],

        [[-4.49274806e-03]],

        [[ 9.03505657e-04]],

        [[

In [29]:
# print(model.predict(mfcc_features_reshaped))
testing = model.predict(mfcc_features_reshaped)
testing

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step


array([[1.]], dtype=float32)

In [31]:
predictions

array([[4.5650523e-09],
       [9.9996328e-01],
       [1.0966087e-02],
       [9.7677767e-01]], dtype=float32)

In [304]:
test_sample = X_test[0].reshape(1, X_test.shape[1], 1, 1)
# print(model.predict(test_sample))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
[[0.6504729]]


In [308]:
test_sample.shape

(1, 39, 1, 1)

In [296]:
print(prediction[0])
if prediction[0] > 0.5:
    print("The audio file is likely a legitimate human voice.")
else:
    print("The audio file is likely AI-generated (deep fake).")


[1.]
The audio file is likely a legitimate human voice.
